version: "3.9"
services:
  prom:
    image: prom/prometheus
    ports:
      - 9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:8.3.3
    ports:
      - 3000:3000
