global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['127.0.0.1:9090']

- job_name: flintlock
  scrape_interval: 5s
  metrics_path: '/machine'
  static_configs:
  - targets: ['192.168.100.35:8090']
