run:
    timeout: 10m
    tests: false
    allow-parallel-runners: true
    skip-dirs:
      - "./*/mock"

linters-settings:
  funlen:
    lines: 110
    statements: 60
  staticcheck:
    go: "1.17"
  stylecheck:
    go: "1.17"
  cyclop:
    max-complexity: 15
    skip-tests: true
  gosec:
    exclude-generated: true
  lll:
    line-length: 120
  misspell:
    locale: GB
  goimports:
    local-prefixes: github.com/weaveworks/flintlock
  govet:
    check-shadowing: true
  nolintlint:
    allow-leading-space: false
    allow-unused: false
    require-explanation: true
    require-specific: false
  varnamelen:
    ignore-names:
    - err
    - wg
    - fs
    - id
    - vm
    - ns
    - ip

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-rules:
  - text: "should not use dot imports|don't use an underscore in package name"
    linters:
    - golint
  - text: "local replacement are not allowed: github.com/weaveworks/flintlock/"
    linters:
    - gomoddirectives
  - text: "sig: func github.com/weaveworks/flintlock/"
    linters:
    - wrapcheck
  - source: "https://"
    linters:
    - lll
  - path: pkg/defaults/
    linters:
    - lll
  - path: _test\.go
    linters:
    - goerr113
    - gocyclo
    - errcheck
    - gosec
    - dupl
    - funlen
    - scopelint
    - testpackage
  - path: internal/version/
    linters:
    - gochecknoglobals
  - path: internal/command/
    linters:
    - exhaustivestruct
    - lll
    - wrapcheck
  - source: "// .* #\\d+"
    linters:
    - godox
  - path: test/e2e/
    linters:
    - goerr113
    - gomnd

linters:
  enable-all: true
  disable:
  - exhaustivestruct
  - golint
  - interfacer
  - ireturn
  - maligned
  - nilnil
  - scopelint
  - tagliatelle
