[tools]
go = "1.25.0"
goreleaser = "2.18.0"
"go:github.com/golangci/golangci-lint/cmd/golangci-lint" = "1.63.4"
"protoc-gen-go" = "1.36.5"
"protoc-gen-go-grpc" = "1.5.1"
ginkgo = "2.22.2"
"go:github.com/golang/mock/mockgen" = "1.6.0"
"go:github.com/google/wire/cmd/wire" = "0.7.0"
"go:github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc" = "1.5.1"
"go:github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway" = "2.26.1"
"go:github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2" = "2.26.1"
buf = "1.72.0"
