package models

import "path"

const (
	// UIDLength is the length of a microvm UID. UIDs are always generated by flintlock as ULIDs.
	UIDLength = 26

	// MaxSocketNameLength is the length of the longest per-microvm socket file name
	// ("cloudhypervisor.sock").
	MaxSocketNameLength = 20

	// SocketSuffixReserve is the headroom reserved for suffixes the VMMs append to socket paths.
	// Firecracker and Cloud Hypervisor listen on "<vsock path>_<port>" for guest initiated
	// connections, where port is a uint32 (up to 10 digits).
	SocketSuffixReserve = 11

	// MaxUnixSocketPathLength is the maximum usable length of a unix socket path on Linux
	// (sun_path is 108 bytes including the terminating NUL).
	MaxUnixSocketPathLength = 107
)

// SocketRoot returns the directory that holds the unix sockets for a microvm. It's keyed only
// by the UID, so its length doesn't depend on the microvm's namespace or name.
func SocketRoot(socketDir string, id VMID) string {
	return path.Join(socketDir, id.UID())
}

// MaxSocketDirLength returns the maximum length of the socket directory that keeps every
// per-microvm socket path within MaxUnixSocketPathLength.
func MaxSocketDirLength() int {
	return MaxUnixSocketPathLength - (1 + UIDLength + 1 + MaxSocketNameLength + SocketSuffixReserve)
}
