// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: services/microvmexec/v1alpha1/microvmexec.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExecCommandRequest is one message in the client->server stream. The first
// message on a stream must carry start; all following messages carry stdin
// (only meaningful if start.has_stdin was set) or stdin_eof.
type ExecCommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecCommandRequest_Start
	//	*ExecCommandRequest_Stdin
	//	*ExecCommandRequest_StdinEof
	Payload       isExecCommandRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecCommandRequest) Reset() {
	*x = ExecCommandRequest{}
	mi := &file_services_microvmexec_v1alpha1_microvmexec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCommandRequest) ProtoMessage() {}

func (x *ExecCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_microvmexec_v1alpha1_microvmexec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecCommandRequest) Descriptor() ([]byte, []int) {
	return file_services_microvmexec_v1alpha1_microvmexec_proto_rawDescGZIP(), []int{0}
}

func (x *ExecCommandRequest) GetPayload() isExecCommandRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecCommandRequest) GetStart() *ExecStart {
	if x != nil {
		if x, ok := x.Payload.(*ExecCommandRequest_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ExecCommandRequest) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecCommandRequest_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ExecCommandRequest) GetStdinEof() bool {
	if x != nil {
		if x, ok := x.Payload.(*ExecCommandRequest_StdinEof); ok {
			return x.StdinEof
		}
	}
	return false
}

type isExecCommandRequest_Payload interface {
	isExecCommandRequest_Payload()
}

type ExecCommandRequest_Start struct {
	Start *ExecStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ExecCommandRequest_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ExecCommandRequest_StdinEof struct {
	StdinEof bool `protobuf:"varint,3,opt,name=stdin_eof,json=stdinEof,proto3,oneof"`
}

func (*ExecCommandRequest_Start) isExecCommandRequest_Payload() {}

func (*ExecCommandRequest_Stdin) isExecCommandRequest_Payload() {}

func (*ExecCommandRequest_StdinEof) isExecCommandRequest_Payload() {}

// ExecStart describes the microvm to target and the command to run, mirroring
// the guest-agent's own exec request fields.
type ExecStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uid is the microvm identifier, as used by MicroVM.GetMicroVM/DeleteMicroVM.
	Uid  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Cmd  string   `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Args []string `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	// cwd is the working directory; empty means the guest-agent's cwd.
	Cwd string `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	// env entries are added to (and override) the guest-agent's environment.
	Env map[string]string `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// shell runs "sh -c <cmd + args joined>" instead of a direct exec.
	Shell bool `protobuf:"varint,6,opt,name=shell,proto3" json:"shell,omitempty"`
	// user, if set, runs the command as that guest system user.
	User string `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	// timeout_seconds bounds the run; 0 means unbounded.
	TimeoutSeconds int32 `protobuf:"varint,8,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// has_stdin tells the server to expect streamed stdin messages.
	HasStdin      bool `protobuf:"varint,9,opt,name=has_stdin,json=hasStdin,proto3" json:"has_stdin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStart) Reset() {
	*x = ExecStart{}
	mi := &file_services_microvmexec_v1alpha1_microvmexec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStart) ProtoMessage() {}

func (x *ExecStart) ProtoReflect() protoreflect.Message {
	mi := &file_services_microvmexec_v1alpha1_microvmexec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStart.ProtoReflect.Descriptor instead.
func (*ExecStart) Descriptor() ([]byte, []int) {
	return file_services_microvmexec_v1alpha1_microvmexec_proto_rawDescGZIP(), []int{1}
}

func (x *ExecStart) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ExecStart) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *ExecStart) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecStart) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ExecStart) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecStart) GetShell() bool {
	if x != nil {
		return x.Shell
	}
	return false
}

func (x *ExecStart) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ExecStart) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ExecStart) GetHasStdin() bool {
	if x != nil {
		return x.HasStdin
	}
	return false
}

// ExecCommandResponse is one message in the server->client stream. Only
// exit_code terminates the stream; error may be sent (typically followed by
// exit_code) without ending the exchange.
type ExecCommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecCommandResponse_Stdout
	//	*ExecCommandResponse_Stderr
	//	*ExecCommandResponse_ExitCode
	//	*ExecCommandResponse_Error
	Payload       isExecCommandResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecCommandResponse) Reset() {
	*x = ExecCommandResponse{}
	mi := &file_services_microvmexec_v1alpha1_microvmexec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecCommandResponse) ProtoMessage() {}

func (x *ExecCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_microvmexec_v1alpha1_microvmexec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecCommandResponse.ProtoReflect.Descriptor instead.
func (*ExecCommandResponse) Descriptor() ([]byte, []int) {
	return file_services_microvmexec_v1alpha1_microvmexec_proto_rawDescGZIP(), []int{2}
}

func (x *ExecCommandResponse) GetPayload() isExecCommandResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecCommandResponse) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecCommandResponse_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecCommandResponse) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecCommandResponse_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecCommandResponse) GetExitCode() int32 {
	if x != nil {
		if x, ok := x.Payload.(*ExecCommandResponse_ExitCode); ok {
			return x.ExitCode
		}
	}
	return 0
}

func (x *ExecCommandResponse) GetError() string {
	if x != nil {
		if x, ok := x.Payload.(*ExecCommandResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isExecCommandResponse_Payload interface {
	isExecCommandResponse_Payload()
}

type ExecCommandResponse_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecCommandResponse_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ExecCommandResponse_ExitCode struct {
	ExitCode int32 `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3,oneof"`
}

type ExecCommandResponse_Error struct {
	Error string `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*ExecCommandResponse_Stdout) isExecCommandResponse_Payload() {}

func (*ExecCommandResponse_Stderr) isExecCommandResponse_Payload() {}

func (*ExecCommandResponse_ExitCode) isExecCommandResponse_Payload() {}

func (*ExecCommandResponse_Error) isExecCommandResponse_Payload() {}

var File_services_microvmexec_v1alpha1_microvmexec_proto protoreflect.FileDescriptor

var file_services_microvmexec_v1alpha1_microvmexec_proto_rawDesc = string([]byte{
	0x0a, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x76, 0x6d, 0x65, 0x78, 0x65, 0x63, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f,
	0x6d, 0x69, 0x63, 0x72, 0x6f, 0x76, 0x6d, 0x65, 0x78, 0x65, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x21, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x76, 0x6d, 0x65, 0x78, 0x65, 0x63, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x22, 0x9c, 0x01, 0x0a, 0x12, 0x45, 0x78, 0x65, 0x63, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x44, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x6d, 0x69, 0x63,
	0x72, 0x6f, 0x76, 0x6d, 0x65, 0x78, 0x65, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x45,
	0x78, 0x65, 0x63, 0x53, 0x74, 0x61, 0x72, 0x74, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x12, 0x16, 0x0a, 0x05, 0x73, 0x74, 0x64, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x64, 0x69, 0x6e, 0x12, 0x1d, 0x0a, 0x09, 0x73, 0x74, 0x64,
	0x69, 0x6e, 0x5f, 0x65, 0x6f, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x08,
	0x73, 0x74, 0x64, 0x69, 0x6e, 0x45, 0x6f, 0x66, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x22, 0xc6, 0x02, 0x0a, 0x09, 0x45, 0x78, 0x65, 0x63, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x77, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x77, 0x64, 0x12, 0x47, 0x0a, 0x03, 0x65,
	0x6e, 0x76, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x76, 0x6d, 0x65, 0x78, 0x65, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x45, 0x78, 0x65,
	0x63, 0x53, 0x74, 0x61, 0x72, 0x74, 0x2e, 0x45, 0x6e, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x03, 0x65, 0x6e, 0x76, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x05, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x27,
	0x0a, 0x0f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x61, 0x73, 0x5f, 0x73,
	0x74, 0x64, 0x69, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x68, 0x61, 0x73, 0x53,
	0x74, 0x64, 0x69, 0x6e, 0x1a, 0x36, 0x0a, 0x08, 0x45, 0x6e, 0x76, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x8b, 0x01, 0x0a,
	0x13, 0x45, 0x78, 0x65, 0x63, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x12, 0x18,
	0x0a, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00,
	0x52, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72, 0x12, 0x1d, 0x0a, 0x09, 0x65, 0x78, 0x69, 0x74,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x65,
	0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42,
	0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x32, 0x90, 0x01, 0x0a, 0x0b, 0x4d,
	0x69, 0x63, 0x72, 0x6f, 0x56, 0x4d, 0x45, 0x78, 0x65, 0x63, 0x12, 0x80, 0x01, 0x0a, 0x0b, 0x45,
	0x78, 0x65, 0x63, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x35, 0x2e, 0x6d, 0x69, 0x63,
	0x72, 0x6f, 0x76, 0x6d, 0x65, 0x78, 0x65, 0x63, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x45,
	0x78, 0x65, 0x63, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x36, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x76, 0x6d, 0x65, 0x78, 0x65, 0x63, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x48, 0x5a,
	0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x71, 0x75,
	0x69, 0x64, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x2d, 0x64, 0x65, 0x76, 0x2f, 0x66, 0x6c, 0x69, 0x6e,
	0x74, 0x6c, 0x6f, 0x63, 0x6b, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x76, 0x6d, 0x65, 0x78, 0x65, 0x63, 0x2f, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_services_microvmexec_v1alpha1_microvmexec_proto_rawDescOnce sync.Once
	file_services_microvmexec_v1alpha1_microvmexec_proto_rawDescData []byte
)

func file_services_microvmexec_v1alpha1_microvmexec_proto_rawDescGZIP() []byte {
	file_services_microvmexec_v1alpha1_microvmexec_proto_rawDescOnce.Do(func() {
		file_services_microvmexec_v1alpha1_microvmexec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_microvmexec_v1alpha1_microvmexec_proto_rawDesc), len(file_services_microvmexec_v1alpha1_microvmexec_proto_rawDesc)))
	})
	return file_services_microvmexec_v1alpha1_microvmexec_proto_rawDescData
}

var file_services_microvmexec_v1alpha1_microvmexec_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_microvmexec_v1alpha1_microvmexec_proto_goTypes = []any{
	(*ExecCommandRequest)(nil),  // 0: microvmexec.services.api.v1alpha1.ExecCommandRequest
	(*ExecStart)(nil),           // 1: microvmexec.services.api.v1alpha1.ExecStart
	(*ExecCommandResponse)(nil), // 2: microvmexec.services.api.v1alpha1.ExecCommandResponse
	nil,                         // 3: microvmexec.services.api.v1alpha1.ExecStart.EnvEntry
}
var file_services_microvmexec_v1alpha1_microvmexec_proto_depIdxs = []int32{
	1, // 0: microvmexec.services.api.v1alpha1.ExecCommandRequest.start:type_name -> microvmexec.services.api.v1alpha1.ExecStart
	3, // 1: microvmexec.services.api.v1alpha1.ExecStart.env:type_name -> microvmexec.services.api.v1alpha1.ExecStart.EnvEntry
	0, // 2: microvmexec.services.api.v1alpha1.MicroVMExec.ExecCommand:input_type -> microvmexec.services.api.v1alpha1.ExecCommandRequest
	2, // 3: microvmexec.services.api.v1alpha1.MicroVMExec.ExecCommand:output_type -> microvmexec.services.api.v1alpha1.ExecCommandResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_services_microvmexec_v1alpha1_microvmexec_proto_init() }
func file_services_microvmexec_v1alpha1_microvmexec_proto_init() {
	if File_services_microvmexec_v1alpha1_microvmexec_proto != nil {
		return
	}
	file_services_microvmexec_v1alpha1_microvmexec_proto_msgTypes[0].OneofWrappers = []any{
		(*ExecCommandRequest_Start)(nil),
		(*ExecCommandRequest_Stdin)(nil),
		(*ExecCommandRequest_StdinEof)(nil),
	}
	file_services_microvmexec_v1alpha1_microvmexec_proto_msgTypes[2].OneofWrappers = []any{
		(*ExecCommandResponse_Stdout)(nil),
		(*ExecCommandResponse_Stderr)(nil),
		(*ExecCommandResponse_ExitCode)(nil),
		(*ExecCommandResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_microvmexec_v1alpha1_microvmexec_proto_rawDesc), len(file_services_microvmexec_v1alpha1_microvmexec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_microvmexec_v1alpha1_microvmexec_proto_goTypes,
		DependencyIndexes: file_services_microvmexec_v1alpha1_microvmexec_proto_depIdxs,
		MessageInfos:      file_services_microvmexec_v1alpha1_microvmexec_proto_msgTypes,
	}.Build()
	File_services_microvmexec_v1alpha1_microvmexec_proto = out.File
	file_services_microvmexec_v1alpha1_microvmexec_proto_goTypes = nil
	file_services_microvmexec_v1alpha1_microvmexec_proto_depIdxs = nil
}
