// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: services/microvmexec/v1alpha1/microvmexec.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MicroVMExec_ExecCommand_FullMethodName = "/microvmexec.services.api.v1alpha1.MicroVMExec/ExecCommand"
)

// MicroVMExecClient is the client API for MicroVMExec service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MicroVMExec runs commands inside a microvm's guest-agent over vsock,
// streaming stdin in and stdout/stderr/exit back out. It requires the target
// microvm to have been created with AllowGuestAgent set, to be in the
// created state, and for the server to have been started with exec enabled.
type MicroVMExecClient interface {
	ExecCommand(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecCommandRequest, ExecCommandResponse], error)
}

type microVMExecClient struct {
	cc grpc.ClientConnInterface
}

func NewMicroVMExecClient(cc grpc.ClientConnInterface) MicroVMExecClient {
	return &microVMExecClient{cc}
}

func (c *microVMExecClient) ExecCommand(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecCommandRequest, ExecCommandResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MicroVMExec_ServiceDesc.Streams[0], MicroVMExec_ExecCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecCommandRequest, ExecCommandResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MicroVMExec_ExecCommandClient = grpc.BidiStreamingClient[ExecCommandRequest, ExecCommandResponse]

// MicroVMExecServer is the server API for MicroVMExec service.
// All implementations should embed UnimplementedMicroVMExecServer
// for forward compatibility.
//
// MicroVMExec runs commands inside a microvm's guest-agent over vsock,
// streaming stdin in and stdout/stderr/exit back out. It requires the target
// microvm to have been created with AllowGuestAgent set, to be in the
// created state, and for the server to have been started with exec enabled.
type MicroVMExecServer interface {
	ExecCommand(grpc.BidiStreamingServer[ExecCommandRequest, ExecCommandResponse]) error
}

// UnimplementedMicroVMExecServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMicroVMExecServer struct{}

func (UnimplementedMicroVMExecServer) ExecCommand(grpc.BidiStreamingServer[ExecCommandRequest, ExecCommandResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ExecCommand not implemented")
}
func (UnimplementedMicroVMExecServer) testEmbeddedByValue() {}

// UnsafeMicroVMExecServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MicroVMExecServer will
// result in compilation errors.
type UnsafeMicroVMExecServer interface {
	mustEmbedUnimplementedMicroVMExecServer()
}

func RegisterMicroVMExecServer(s grpc.ServiceRegistrar, srv MicroVMExecServer) {
	// If the following call pancis, it indicates UnimplementedMicroVMExecServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MicroVMExec_ServiceDesc, srv)
}

func _MicroVMExec_ExecCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MicroVMExecServer).ExecCommand(&grpc.GenericServerStream[ExecCommandRequest, ExecCommandResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MicroVMExec_ExecCommandServer = grpc.BidiStreamingServer[ExecCommandRequest, ExecCommandResponse]

// MicroVMExec_ServiceDesc is the grpc.ServiceDesc for MicroVMExec service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MicroVMExec_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "microvmexec.services.api.v1alpha1.MicroVMExec",
	HandlerType: (*MicroVMExecServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecCommand",
			Handler:       _MicroVMExec_ExecCommand_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "services/microvmexec/v1alpha1/microvmexec.proto",
}
