// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: services/microvmsshproxy/v1alpha1/microvmsshproxy.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MicroVMSSHProxy_SSHProxy_FullMethodName = "/microvmsshproxy.services.api.v1alpha1.MicroVMSSHProxy/SSHProxy"
)

// MicroVMSSHProxyClient is the client API for MicroVMSSHProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MicroVMSSHProxy tunnels a raw byte stream to a microvm's guest-agent ssh
// port, which itself proxies straight to the guest's local sshd - the agent
// performs no authentication of its own; sshd owns auth, PTY and SFTP. It
// requires the target microvm to have been created with AllowGuestAgent set,
// to be in the created state, and for the server to have been started with
// ssh proxying enabled.
type MicroVMSSHProxyClient interface {
	SSHProxy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SSHProxyRequest, SSHProxyResponse], error)
}

type microVMSSHProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewMicroVMSSHProxyClient(cc grpc.ClientConnInterface) MicroVMSSHProxyClient {
	return &microVMSSHProxyClient{cc}
}

func (c *microVMSSHProxyClient) SSHProxy(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SSHProxyRequest, SSHProxyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MicroVMSSHProxy_ServiceDesc.Streams[0], MicroVMSSHProxy_SSHProxy_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SSHProxyRequest, SSHProxyResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MicroVMSSHProxy_SSHProxyClient = grpc.BidiStreamingClient[SSHProxyRequest, SSHProxyResponse]

// MicroVMSSHProxyServer is the server API for MicroVMSSHProxy service.
// All implementations should embed UnimplementedMicroVMSSHProxyServer
// for forward compatibility.
//
// MicroVMSSHProxy tunnels a raw byte stream to a microvm's guest-agent ssh
// port, which itself proxies straight to the guest's local sshd - the agent
// performs no authentication of its own; sshd owns auth, PTY and SFTP. It
// requires the target microvm to have been created with AllowGuestAgent set,
// to be in the created state, and for the server to have been started with
// ssh proxying enabled.
type MicroVMSSHProxyServer interface {
	SSHProxy(grpc.BidiStreamingServer[SSHProxyRequest, SSHProxyResponse]) error
}

// UnimplementedMicroVMSSHProxyServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMicroVMSSHProxyServer struct{}

func (UnimplementedMicroVMSSHProxyServer) SSHProxy(grpc.BidiStreamingServer[SSHProxyRequest, SSHProxyResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SSHProxy not implemented")
}
func (UnimplementedMicroVMSSHProxyServer) testEmbeddedByValue() {}

// UnsafeMicroVMSSHProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MicroVMSSHProxyServer will
// result in compilation errors.
type UnsafeMicroVMSSHProxyServer interface {
	mustEmbedUnimplementedMicroVMSSHProxyServer()
}

func RegisterMicroVMSSHProxyServer(s grpc.ServiceRegistrar, srv MicroVMSSHProxyServer) {
	// If the following call pancis, it indicates UnimplementedMicroVMSSHProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MicroVMSSHProxy_ServiceDesc, srv)
}

func _MicroVMSSHProxy_SSHProxy_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MicroVMSSHProxyServer).SSHProxy(&grpc.GenericServerStream[SSHProxyRequest, SSHProxyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MicroVMSSHProxy_SSHProxyServer = grpc.BidiStreamingServer[SSHProxyRequest, SSHProxyResponse]

// MicroVMSSHProxy_ServiceDesc is the grpc.ServiceDesc for MicroVMSSHProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MicroVMSSHProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "microvmsshproxy.services.api.v1alpha1.MicroVMSSHProxy",
	HandlerType: (*MicroVMSSHProxyServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SSHProxy",
			Handler:       _MicroVMSSHProxy_SSHProxy_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "services/microvmsshproxy/v1alpha1/microvmsshproxy.proto",
}
