// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: services/microvmsshproxy/v1alpha1/microvmsshproxy.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SSHProxyRequest is one message in the client->server stream. The first
// message on a stream must carry uid; all following messages carry data
// bytes to forward toward the guest's sshd.
type SSHProxyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SSHProxyRequest_Uid
	//	*SSHProxyRequest_Data
	Payload       isSSHProxyRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHProxyRequest) Reset() {
	*x = SSHProxyRequest{}
	mi := &file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHProxyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHProxyRequest) ProtoMessage() {}

func (x *SSHProxyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHProxyRequest.ProtoReflect.Descriptor instead.
func (*SSHProxyRequest) Descriptor() ([]byte, []int) {
	return file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_rawDescGZIP(), []int{0}
}

func (x *SSHProxyRequest) GetPayload() isSSHProxyRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SSHProxyRequest) GetUid() string {
	if x != nil {
		if x, ok := x.Payload.(*SSHProxyRequest_Uid); ok {
			return x.Uid
		}
	}
	return ""
}

func (x *SSHProxyRequest) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*SSHProxyRequest_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isSSHProxyRequest_Payload interface {
	isSSHProxyRequest_Payload()
}

type SSHProxyRequest_Uid struct {
	// uid is the microvm identifier, as used by MicroVM.GetMicroVM/DeleteMicroVM.
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3,oneof"`
}

type SSHProxyRequest_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*SSHProxyRequest_Uid) isSSHProxyRequest_Payload() {}

func (*SSHProxyRequest_Data) isSSHProxyRequest_Payload() {}

// SSHProxyResponse carries raw bytes received from the guest's sshd.
type SSHProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHProxyResponse) Reset() {
	*x = SSHProxyResponse{}
	mi := &file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHProxyResponse) ProtoMessage() {}

func (x *SSHProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHProxyResponse.ProtoReflect.Descriptor instead.
func (*SSHProxyResponse) Descriptor() ([]byte, []int) {
	return file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_rawDescGZIP(), []int{1}
}

func (x *SSHProxyResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto protoreflect.FileDescriptor

var file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_rawDesc = string([]byte{
	0x0a, 0x37, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x76, 0x6d, 0x73, 0x73, 0x68, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x76, 0x6d, 0x73, 0x73, 0x68, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x25, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x76, 0x6d, 0x73, 0x73, 0x68, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x22, 0x46, 0x0a, 0x0f, 0x53, 0x53, 0x48, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x09, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x26, 0x0a, 0x10, 0x53, 0x53, 0x48, 0x50,
	0x72, 0x6f, 0x78, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x32, 0x92, 0x01, 0x0a, 0x0f, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x56, 0x4d, 0x53, 0x53, 0x48, 0x50,
	0x72, 0x6f, 0x78, 0x79, 0x12, 0x7f, 0x0a, 0x08, 0x53, 0x53, 0x48, 0x50, 0x72, 0x6f, 0x78, 0x79,
	0x12, 0x36, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x76, 0x6d, 0x73, 0x73, 0x68, 0x70, 0x72, 0x6f,
	0x78, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x53, 0x53, 0x48, 0x50, 0x72, 0x6f, 0x78,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x37, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x76, 0x6d, 0x73, 0x73, 0x68, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2e, 0x53, 0x53, 0x48, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x4c, 0x5a, 0x4a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x2d,
	0x64, 0x65, 0x76, 0x2f, 0x66, 0x6c, 0x69, 0x6e, 0x74, 0x6c, 0x6f, 0x63, 0x6b, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f,
	0x76, 0x6d, 0x73, 0x73, 0x68, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_rawDescOnce sync.Once
	file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_rawDescData []byte
)

func file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_rawDescGZIP() []byte {
	file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_rawDescOnce.Do(func() {
		file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_rawDesc), len(file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_rawDesc)))
	})
	return file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_rawDescData
}

var file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_goTypes = []any{
	(*SSHProxyRequest)(nil),  // 0: microvmsshproxy.services.api.v1alpha1.SSHProxyRequest
	(*SSHProxyResponse)(nil), // 1: microvmsshproxy.services.api.v1alpha1.SSHProxyResponse
}
var file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_depIdxs = []int32{
	0, // 0: microvmsshproxy.services.api.v1alpha1.MicroVMSSHProxy.SSHProxy:input_type -> microvmsshproxy.services.api.v1alpha1.SSHProxyRequest
	1, // 1: microvmsshproxy.services.api.v1alpha1.MicroVMSSHProxy.SSHProxy:output_type -> microvmsshproxy.services.api.v1alpha1.SSHProxyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_init() }
func file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_init() {
	if File_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto != nil {
		return
	}
	file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_msgTypes[0].OneofWrappers = []any{
		(*SSHProxyRequest_Uid)(nil),
		(*SSHProxyRequest_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_rawDesc), len(file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_goTypes,
		DependencyIndexes: file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_depIdxs,
		MessageInfos:      file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_msgTypes,
	}.Build()
	File_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto = out.File
	file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_goTypes = nil
	file_services_microvmsshproxy_v1alpha1_microvmsshproxy_proto_depIdxs = nil
}
