name: bundlebot

on:
  workflow_dispatch: {}
  push:
    branches: # TODO remove
      - bundlebot
  schedule:
    - cron: 0 0 * * 1 # every Monday at 00:00

jobs:
  bundler:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Cache go-build and mod
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build/
            ~/go/pkg/mod/
          key: go-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-
      - name: Install Dependabot Bundler
        run: |
          go install github.com/Skarlso/dependabot-bundler@v0.0.3
      - name: Run Dependabot Bundler
        run: |
          dependabot-bundler \
            --token ${{ secrets.GITHUB_TOKEN }} \
            --owner weaveworks-liquidmetal \
            --repo flintlock \
            --labels 'area/dependencies'
