name: bundlebot

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 0 * * 1 # every Monday at 00:00

jobs:
  bundler:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version-file: "${{ github.workspace }}/go.mod"
          check-latest: true
          cache: false
      - name: Cache go-build and mod
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: |
            ~/.cache/go-build/
            ~/go/pkg/mod/
          key: go-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-
      - name: Install Dependabot Bundler
        run: |
          go install github.com/Skarlso/dependabot-bundler@v0.0.17
      - name: Run Dependabot Bundler
        run: |
          dependabot-bundler \
            --token ${{ secrets.GITHUB_TOKEN }} \
            --owner liquidmetal-dev \
            --repo flintlock \
            --labels 'area/dependency,kind/cleanup,user-signing-required' \
            --pr-title 'chore(deps): Bundle dependabot pull requests'
