name: Documentation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - uses: actions/setup-go@v3
        with:
          go-version-file: "${{ github.workspace }}/go.mod"
      - name: Build docs
        run: make docs-build
  release:
    if: ${{ github.event_name != 'pull_request' && github.repository_owner == 'liquidmetal-dev' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - uses: actions/setup-go@v3
        with:
          go-version-file: "${{ github.workspace }}/go.mod"
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.BOT_DEPLOY_KEY }}
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
          DEPLOYMENT_BRANCH: gh-pages
        run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "liquidmetal-docs-bot"
          make docs-deploy
