name: run e2e tests

on: [pull_request]

jobs:
  test:
    name: test-e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: debug
        uses: mxschmitt/action-tmate@v3
      - name: E2E tests in container
        run: make test-e2e-docker
