name: Test docs build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build docusaurus
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: 'userdocs/yarn.lock'
      - name: Install dependencies
        working-directory: ./userdocs
        run: yarn install --frozen-lockfile
      - name: Build website
        working-directory: ./userdocs
        run: yarn build